name: 'bypass-cloudflare-for-github-action'
description: 'bypass cloudflare for github action, never receive 403 forbidden from cloudflare again.'
author: 'Snowdream Tech'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'activity'
  color: "green"

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
